mark_as_advanced(	CAUDIO_BUILD_EAX_PLUGIN 
					CAUDIO_BUILD_MP3DECODER_PLUGIN
					CAUDIO_ENABLE_OGG
					CAUDIO_ENABLE_WAV
					CAUDIO_ENABLE_DEFAULT_FILESYSTEM
					CAUDIO_ENABLE_DEFAULT_FILE_LOGGER
					CAUDIO_ENABLE_DEFAULT_CONSOLE_LOGGER
					CAUDIO_ENABLE_THREAD_SAFETY
					CAUDIO_ENABLE_STD_MEMORY_ALLOCATOR
					CAUDIO_ENABLE_REROUTE_STL_ALLOCATIONS
					CAUDIO_ENABLE_MEMORYTRACKER
					CAUDIO_ENABLE_MEMORY_LOG_ALL_ALLOCATIONS
					CAUDIO_ENABLE_MEMORY_STATISTICS	)

set(CAUDIO_SET_STATIC 0)
set(CAUDIO_SET_ENABLE_EFX 0)
set(CAUDIO_SET_ENABLE_OGG 1)
set(CAUDIO_SET_ENABLE_WAV 1)
set(CAUDIO_SET_ENABLE_DEFAULT_FILESYSTEM 1)
set(CAUDIO_SET_ENABLE_DEFAULT_FILE_LOGGER 1)
set(CAUDIO_SET_ENABLE_DEFAULT_CONSOLE_LOGGER 1)
set(CAUDIO_SET_ENABLE_THREAD_SAFETY 1)
set(CAUDIO_SET_ENABLE_STD_MEMORY_ALLOCATOR 1)
set(CAUDIO_SET_ENABLE_REROUTE_STL_ALLOCATIONS 1)
set(CAUDIO_SET_ENABLE_MEMORYTRACKER 0)
set(CAUDIO_SET_ENABLE_MEMORY_LOG_ALL_ALLOCATIONS 0)
set(CAUDIO_SET_ENABLE_MEMORY_STATISTICS 0)

if(CAUDIO_STATIC)
	set(CAUDIO_SET_STATIC 1)
else()
	set(CAUDIO_SET_STATIC 0)
endif()

if(CAUDIO_BUILD_EAX_PLUGIN)
	set(CAUDIO_SET_ENABLE_EFX 1)
else()
	set(CAUDIO_SET_ENABLE_EFX 0)
endif()

if(CAUDIO_ENABLE_OGG)
  set(CAUDIO_SET_ENABLE_OGG 1)
else()
  set(CAUDIO_SET_ENABLE_OGG 0)
endif()

if(CAUDIO_ENABLE_WAV)
	set(CAUDIO_SET_ENABLE_WAV 1)
else()
	set(CAUDIO_SET_ENABLE_WAV 0)
endif()

if(CAUDIO_ENABLE_DEFAULT_FILESYSTEM)
	set(CAUDIO_SET_ENABLE_DEFAULT_FILESYSTEM 1)
else()
	set(CAUDIO_SET_ENABLE_DEFAULT_FILESYSTEM 0)
endif()

if(CAUDIO_ENABLE_DEFAULT_FILE_LOGGER)
	set(CAUDIO_SET_ENABLE_DEFAULT_FILE_LOGGER 1)
else()
	set(CAUDIO_SET_ENABLE_DEFAULT_FILE_LOGGER 0)
endif()

if(CAUDIO_ENABLE_DEFAULT_CONSOLE_LOGGER)
	set(CAUDIO_SET_ENABLE_DEFAULT_CONSOLE_LOGGER 1)
else()
	set(CAUDIO_SET_ENABLE_DEFAULT_CONSOLE_LOGGER 0)
endif()

if(CAUDIO_ENABLE_THREAD_SAFETY)
	set(CAUDIO_SET_ENABLE_THREAD_SAFETY 1)
else()
	set(CAUDIO_SET_ENABLE_THREAD_SAFETY 0)
endif()

if(CAUDIO_ENABLE_STD_MEMORY_ALLOCATOR)
	set(CAUDIO_SET_ENABLE_STD_MEMORY_ALLOCATOR 1)
else()
	set(CAUDIO_SET_ENABLE_STD_MEMORY_ALLOCATOR 0)
endif()

if(CAUDIO_ENABLE_REROUTE_STL_ALLOCATIONS)
	set(CAUDIO_SET_ENABLE_REROUTE_STL_ALLOCATIONS 1)
else()
	set(CAUDIO_SET_ENABLE_REROUTE_STL_ALLOCATIONS 0)
endif()

if(CAUDIO_ENABLE_MEMORYTRACKER)
	set(CAUDIO_SET_ENABLE_MEMORYTRACKER 1)
else()
	set(CAUDIO_SET_ENABLE_MEMORYTRACKER 0)
endif()

if(CAUDIO_ENABLE_MEMORY_LOG_ALL_ALLOCATIONS)
	set(CAUDIO_SET_ENABLE_MEMORY_LOG_ALL_ALLOCATIONS 1)
else()
	set(CAUDIO_SET_ENABLE_MEMORY_LOG_ALL_ALLOCATIONS 0)
endif()

if(CAUDIO_ENABLE_MEMORY_STATISTICS)
	set(CAUDIO_SET_ENABLE_MEMORY_STATISTICS 1)
else()
	set(CAUDIO_SET_ENABLE_MEMORY_STATISTICS 0)
endif()

if(CAUDIO_STATIC)
	set(CAUDIO_LIB_TYPE STATIC)
else()
	set(CAUDIO_LIB_TYPE SHARED)
endif()