#pragma once

enum class EGLVertexAttrib
{
	ATTRIB_POSITION,
	ATTRIB_COLOR,
	ATTRIB_COLOR1,
	ATTRIB_TEX_COORD,
	ATTRIB_TEX_COORD1,
	ATTRIB_TEX_COORD2,
	ATTRIB_TEX_COORD3,
	ATTRIB_NORMAL,
	ATTRIB_BLEND_WEIGHT,
	ATTRIB_BLEND_INDEX,
	ATTRIB_MAX,
};