/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace cAudio {

using System;
using System.Runtime.InteropServices;

public class IListener : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IListener(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(IListener obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~IListener() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cAudioCSharpWrapperPINVOKE.delete_IListener(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public virtual void setPosition(cVector3 pos) {
    cAudioCSharpWrapperPINVOKE.IListener_setPosition(swigCPtr, cVector3.getCPtr(pos));
    if (cAudioCSharpWrapperPINVOKE.SWIGPendingException.Pending) throw cAudioCSharpWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void setDirection(cVector3 dir) {
    cAudioCSharpWrapperPINVOKE.IListener_setDirection(swigCPtr, cVector3.getCPtr(dir));
    if (cAudioCSharpWrapperPINVOKE.SWIGPendingException.Pending) throw cAudioCSharpWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void setUpVector(cVector3 up) {
    cAudioCSharpWrapperPINVOKE.IListener_setUpVector(swigCPtr, cVector3.getCPtr(up));
    if (cAudioCSharpWrapperPINVOKE.SWIGPendingException.Pending) throw cAudioCSharpWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void setVelocity(cVector3 vel) {
    cAudioCSharpWrapperPINVOKE.IListener_setVelocity(swigCPtr, cVector3.getCPtr(vel));
    if (cAudioCSharpWrapperPINVOKE.SWIGPendingException.Pending) throw cAudioCSharpWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void setMasterVolume(float volume) {
    cAudioCSharpWrapperPINVOKE.IListener_setMasterVolume(swigCPtr, volume);
  }

  public virtual void move(cVector3 pos) {
    cAudioCSharpWrapperPINVOKE.IListener_move(swigCPtr, cVector3.getCPtr(pos));
    if (cAudioCSharpWrapperPINVOKE.SWIGPendingException.Pending) throw cAudioCSharpWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual cVector3 getPosition() {
    cVector3 ret = new cVector3(cAudioCSharpWrapperPINVOKE.IListener_getPosition(swigCPtr), true);
    return ret;
  }

  public virtual cVector3 getDirection() {
    cVector3 ret = new cVector3(cAudioCSharpWrapperPINVOKE.IListener_getDirection(swigCPtr), true);
    return ret;
  }

  public virtual cVector3 getUpVector() {
    cVector3 ret = new cVector3(cAudioCSharpWrapperPINVOKE.IListener_getUpVector(swigCPtr), true);
    return ret;
  }

  public virtual cVector3 getVelocity() {
    cVector3 ret = new cVector3(cAudioCSharpWrapperPINVOKE.IListener_getVelocity(swigCPtr), true);
    return ret;
  }

  public virtual float getMasterVolume() {
    float ret = cAudioCSharpWrapperPINVOKE.IListener_getMasterVolume(swigCPtr);
    return ret;
  }

}

}
