/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace cAudio {

using System;
using System.Runtime.InteropServices;

public class IRefCounted : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IRefCounted(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(IRefCounted obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~IRefCounted() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cAudioCSharpWrapperPINVOKE.delete_IRefCounted(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public IRefCounted() : this(cAudioCSharpWrapperPINVOKE.new_IRefCounted(), true) {
  }

  public virtual void grab() {
    cAudioCSharpWrapperPINVOKE.IRefCounted_grab(swigCPtr);
  }

  public virtual bool drop() {
    bool ret = cAudioCSharpWrapperPINVOKE.IRefCounted_drop(swigCPtr);
    return ret;
  }

  public int getReferenceCount() {
    int ret = cAudioCSharpWrapperPINVOKE.IRefCounted_getReferenceCount(swigCPtr);
    return ret;
  }

}

}
