/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace cAudio {

public enum LogLevel {
  ELL_DEBUG,
  ELL_INFO,
  ELL_WARNING,
  ELL_ERROR,
  ELL_CRITICAL,
  ELL_COUNT
}

}
