/** @author LiXizhi  */
DROP TABLE IF EXISTS [NPC];
CREATE TABLE [NPC](
	[ID] INTEGER PRIMARY KEY,
	[Name] [nchar](20) UNIQUE NOT NULL,
	[AssetName] [nchar](10)  NOT NULL,
	[IsGlobal] [smallint] NOT NULL DEFAULT ((1)),
	[SnapToTerrain] [smallint] NOT NULL DEFAULT ((1)),
	[Radius] [float] NOT NULL DEFAULT ((0.35)),
	[Facing] [float] NOT NULL DEFAULT ((0)),
	[Scaling] [float] NOT NULL DEFAULT ((1)),
	[posX] [float] NOT NULL DEFAULT ((0)),
	[posY] [float] NOT NULL DEFAULT ((0)),
	[posZ] [float] NOT NULL DEFAULT ((0)),
	[CharacterType] [int] NOT NULL DEFAULT ((0)),
	[MentalState0] [int] NOT NULL DEFAULT ((0)),
	[MentalState1] [int] NOT NULL DEFAULT ((0)),
	[MentalState2] [int] NOT NULL DEFAULT ((0)),
	[MentalState3] [int] NOT NULL DEFAULT ((0)),
	[LifePoint] [float] NOT NULL DEFAULT ((100)),
	[Age] [float] NOT NULL DEFAULT ((1)),
	[Height] [float] NOT NULL DEFAULT ((1.78)),
	[Weight] [float] NOT NULL DEFAULT ((55)),
	[Occupation] [int] NOT NULL DEFAULT ((0)),
	[RaceSex] [int] NOT NULL DEFAULT ((0)),
	[Strength] [float] NOT NULL DEFAULT ((0)),
	[Dexterity] [float] NOT NULL DEFAULT ((0)),
	[Intelligence] [float] NOT NULL DEFAULT ((0)),
	[BaseDefense] [float] NOT NULL DEFAULT ((0)),
	[Defense] [float] NOT NULL DEFAULT ((0)),
	[Defenseflat] [float] NOT NULL DEFAULT ((0)),
	[DefenseMental] [float] NOT NULL DEFAULT ((0)),
	[BaseAttack] [float] NOT NULL DEFAULT ((0)),
	[AttackMelee] [float] NOT NULL DEFAULT ((0)),
	[AttackRanged] [float] NOT NULL DEFAULT ((0)),
	[AttackMental] [float] NOT NULL DEFAULT ((0)),
	[MaxLifeLoad] [float] NOT NULL DEFAULT ((10)),
	[HeroPoints] [int] NOT NULL DEFAULT ((0)),
	[PerceptiveRadius] [float] NOT NULL DEFAULT ((7)),
	[SentientRadius] [float] NOT NULL DEFAULT ((50)),
	[GroupID] [int] NOT NULL DEFAULT ((0)),
	[SentientField] [int] NOT NULL DEFAULT ((0)),
	[OnLoadScript] [nvarchar](2048) NULL,
	[CustomAppearance] [nvarchar](255) NULL
);
