# protoc runs on the build host, not inside WebAssembly. Match ONNX's pinned
# protobuf version and reuse the URLs/checksums in its dependency manifest.
function(web_robot_check_protoc executable)
    execute_process(COMMAND "${executable}" --version
        RESULT_VARIABLE result OUTPUT_VARIABLE version ERROR_VARIABLE error
        OUTPUT_STRIP_TRAILING_WHITESPACE TIMEOUT 10)
    if(NOT result STREQUAL "0" OR NOT version STREQUAL "libprotoc 3.21.12")
        message(FATAL_ERROR "Robot ONNX requires host protoc 3.21.12: ${executable} (${version}; ${error})")
    endif()
endfunction()

set(ONNX_CUSTOM_PROTOC_EXECUTABLE "" CACHE FILEPATH "Optional host protoc 3.21.12 for robot ONNX")
if(ONNX_CUSTOM_PROTOC_EXECUTABLE)
    web_robot_check_protoc("${ONNX_CUSTOM_PROTOC_EXECUTABLE}")
    set(_robot_protoc "${ONNX_CUSTOM_PROTOC_EXECUTABLE}")
else()
    set(_robot_protoc_suffix "")
    if(CMAKE_HOST_WIN32)
        set(_robot_protoc_platform win64)
        set(_robot_protoc_suffix .exe)
    elseif(CMAKE_HOST_APPLE)
        set(_robot_protoc_platform mac_universal)
    elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux" AND CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "^(x86_64|amd64)$")
        set(_robot_protoc_platform linux_x64)
    elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux" AND CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "^(aarch64|arm64)$")
        set(_robot_protoc_platform linux_aarch64)
    else()
        message(FATAL_ERROR "Set ONNX_CUSTOM_PROTOC_EXECUTABLE to host protoc 3.21.12 for this platform")
    endif()
    set(_robot_protoc_dir "${CMAKE_BINARY_DIR}/robot-host-tools/protoc-21.12-${_robot_protoc_platform}")
    set(_robot_protoc "${_robot_protoc_dir}/bin/protoc${_robot_protoc_suffix}")
    if(NOT EXISTS "${_robot_protoc}")
        file(STRINGS "${_robot_onnx_source}/cmake/deps.txt" _robot_protoc_entries
            REGEX "^protoc_${_robot_protoc_platform};")
        if(NOT _robot_protoc_entries)
            message(FATAL_ERROR "Missing pinned protoc manifest entry: ${_robot_protoc_platform}")
        endif()
        list(GET _robot_protoc_entries 0 _robot_protoc_entry)
        list(LENGTH _robot_protoc_entry _robot_entry_length)
        if(NOT _robot_entry_length EQUAL 3)
            message(FATAL_ERROR "Missing pinned protoc manifest entry: ${_robot_protoc_platform}")
        endif()
        list(GET _robot_protoc_entry 1 _robot_protoc_url)
        list(GET _robot_protoc_entry 2 _robot_protoc_sha1)
        file(MAKE_DIRECTORY "${_robot_protoc_dir}")
        set(_robot_protoc_archive "${_robot_protoc_dir}/download.zip")
        set(_robot_archive_valid FALSE)
        if(EXISTS "${_robot_protoc_archive}")
            file(SHA1 "${_robot_protoc_archive}" _robot_actual_sha1)
            if(_robot_actual_sha1 STREQUAL _robot_protoc_sha1)
                set(_robot_archive_valid TRUE)
            endif()
        endif()
        if(NOT _robot_archive_valid)
            message(STATUS "Web robot: downloading pinned host protoc (${_robot_protoc_platform})")
            file(DOWNLOAD "${_robot_protoc_url}" "${_robot_protoc_archive}"
                STATUS _robot_download_status TIMEOUT 120 INACTIVITY_TIMEOUT 30 TLS_VERIFY ON)
            list(GET _robot_download_status 0 _robot_download_code)
            if(NOT _robot_download_code EQUAL 0)
                find_program(_robot_curl NAMES curl NO_CMAKE_FIND_ROOT_PATH)
                if(NOT _robot_curl)
                    message(FATAL_ERROR "protoc download failed; install curl for HTTP/1.1 retry or set ONNX_CUSTOM_PROTOC_EXECUTABLE")
                endif()
                message(STATUS "Web robot: retrying protoc download with curl HTTP/1.1")
                execute_process(COMMAND "${_robot_curl}" --http1.1 --fail --location
                    --retry 2 --connect-timeout 20 --max-time 120 --silent --show-error
                    --output "${_robot_protoc_archive}" "${_robot_protoc_url}"
                    RESULT_VARIABLE _robot_curl_result TIMEOUT 400)
                if(NOT _robot_curl_result STREQUAL "0")
                    message(FATAL_ERROR "protoc download failed; provide ONNX_CUSTOM_PROTOC_EXECUTABLE or retry with a working process proxy")
                endif()
            endif()
            file(SHA1 "${_robot_protoc_archive}" _robot_actual_sha1)
            if(NOT _robot_actual_sha1 STREQUAL _robot_protoc_sha1)
                message(FATAL_ERROR "Downloaded protoc checksum does not match the pinned ONNX manifest")
            endif()
        endif()
        file(ARCHIVE_EXTRACT INPUT "${_robot_protoc_archive}" DESTINATION "${_robot_protoc_dir}")
    endif()
    web_robot_check_protoc("${_robot_protoc}")
endif()
message(STATUS "Web robot: using host protoc ${_robot_protoc}")
