if(NOT EMSCRIPTEN OR NOT EMSCRIPTEN_SINGLE_THREAD)
    message(FATAL_ERROR "Web robot integration currently requires single-thread Emscripten")
endif()
include(${CMAKE_CURRENT_LIST_DIR}/WebRobotLinkFeatures.cmake)
get_filename_component(_robot_branch_root "${CMAKE_CURRENT_LIST_DIR}/../../Server/trunk" REALPATH)
set(ROBOT_DEPENDENCY_ROOT "${_robot_branch_root}" CACHE PATH "Versioned dependency sources inside this WASM checkout")
get_filename_component(_robot_configured_root "${ROBOT_DEPENDENCY_ROOT}" REALPATH)
if(NOT _robot_configured_root STREQUAL _robot_branch_root)
    message(FATAL_ERROR "Robot C++ dependencies must be inside this WASM checkout: ${_robot_branch_root}")
endif()
if(NOT EXISTS "${ROBOT_DEPENDENCY_ROOT}/mujoco-3.10.0/CMakeLists.txt"
   OR NOT EXISTS "${ROBOT_DEPENDENCY_ROOT}/onnxruntime-1.27.1/cmake/CMakeLists.txt")
    message(FATAL_ERROR "The WASM checkout must contain the pinned MuJoCo/ONNX sources in Server/trunk")
endif()
set(MUJOCO_WASM_THREADS OFF CACHE BOOL "" FORCE)
set(MUJOCO_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(MUJOCO_BUILD_TESTS_WASM OFF CACHE BOOL "" FORCE)
set(MUJOCO_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(MUJOCO_BUILD_SIMULATE OFF CACHE BOOL "" FORCE)
set(MUJOCO_BUILD_STUDIO OFF CACHE BOOL "" FORCE)
set(MUJOCO_USE_FILAMENT OFF CACHE BOOL "" FORCE)
add_subdirectory("${ROBOT_DEPENDENCY_ROOT}/mujoco-3.10.0" "${CMAKE_BINARY_DIR}/mujoco" EXCLUDE_FROM_ALL)
# cp_old puts Emscripten link settings in global compile flags; MuJoCo's
# -Werror must not turn those harmless driver diagnostics into errors.
target_compile_options(mujoco PRIVATE -Wno-unused-command-line-argument)
include(${CMAKE_CURRENT_LIST_DIR}/WebRobotOnnx.cmake)
set(ROBOT_TEST_ASSET_ROOT "" CACHE PATH "MicroDuck walking assets for the WASM smoke test")
if(EXISTS "${ROBOT_TEST_ASSET_ROOT}/mujoco/scene_ball.xml")
    add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/../tests" "${CMAKE_BINARY_DIR}/robot-tests-build")
endif()
