/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace cAudio {

public enum AudioFormats {
  EAF_8BIT_MONO,
  EAF_8BIT_STEREO,
  EAF_16BIT_MONO,
  EAF_16BIT_STEREO
}

}
