/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace cAudio {

using System;
using System.Runtime.InteropServices;

public class IAudioDeviceContext : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IAudioDeviceContext(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(IAudioDeviceContext obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~IAudioDeviceContext() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cAudioCSharpWrapperPINVOKE.delete_IAudioDeviceContext(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public virtual bool initialize(string deviceName, int outputFrequency, int eaxEffectSlots) {
    bool ret = cAudioCSharpWrapperPINVOKE.IAudioDeviceContext_initialize(swigCPtr, deviceName, outputFrequency, eaxEffectSlots);
    return ret;
  }

  public virtual void shutDown() {
    cAudioCSharpWrapperPINVOKE.IAudioDeviceContext_shutDown(swigCPtr);
  }

  public virtual void update() {
    cAudioCSharpWrapperPINVOKE.IAudioDeviceContext_update(swigCPtr);
  }

  public virtual IAudioManager getAudioManager() {
    IntPtr cPtr = cAudioCSharpWrapperPINVOKE.IAudioDeviceContext_getAudioManager(swigCPtr);
    IAudioManager ret = (cPtr == IntPtr.Zero) ? null : new IAudioManager(cPtr, false);
    return ret;
  }

  public virtual SWIGTYPE_p_cAudio__IAudioEffects getEffects() {
    IntPtr cPtr = cAudioCSharpWrapperPINVOKE.IAudioDeviceContext_getEffects(swigCPtr);
    SWIGTYPE_p_cAudio__IAudioEffects ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_cAudio__IAudioEffects(cPtr, false);
    return ret;
  }

}

}
