# Run with: cmake -P NPLRuntime/tests/WebRobotDefaults.cmake
set(_defaults "${CMAKE_CURRENT_LIST_DIR}/../cmake/WebRobotDefaults.cmake")
foreach(_case fresh legacy-off)
    unset(NPLRUNTIME_WEB_ROBOT CACHE)
    if(_case STREQUAL "legacy-off")
        set(NPLRUNTIME_WEB_ROBOT OFF CACHE BOOL "Old default")
    endif()
    set(EMSCRIPTEN ON)
    set(EMSCRIPTEN_SINGLE_THREAD ON)
    include("${_defaults}")
    if(NOT NPLRUNTIME_WEB_ROBOT)
        message(FATAL_ERROR "Single-thread Web robot support missing: ${_case}")
    endif()
    get_property(_cached CACHE NPLRUNTIME_WEB_ROBOT PROPERTY VALUE)
    if(NOT _cached)
        message(FATAL_ERROR "The old cache was not upgraded")
    endif()
endforeach()
foreach(_platform native web-threads)
    unset(NPLRUNTIME_WEB_ROBOT CACHE)
    set(EMSCRIPTEN OFF)
    if(_platform STREQUAL "web-threads")
        set(EMSCRIPTEN ON)
    endif()
    set(EMSCRIPTEN_SINGLE_THREAD OFF)
    include("${_defaults}")
    if(NPLRUNTIME_WEB_ROBOT)
        message(FATAL_ERROR "Robot support was forced on an unsupported platform: ${_platform}")
    endif()
endforeach()
message(STATUS "Web robot default and legacy-cache checks passed")
