# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: dir 7z 
      run: dir 'C:\Program Files\7-Zip'
      
    - name: exe 72
      run: 'C:\Program Files\7-Zip\7z'
