name: Windows

on:
  push:
    branches: [ cp_old ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2019

    steps:
    # 拉取代码
    - name: pull source code
      uses: actions/checkout@v3

    # 安装cmake
    - name: install cmake
      uses: lukka/get-cmake@latest

    - name: install boost
      uses: MarkusJx/install-boost@v2.3.0
      id: install-boost
      with:
        boost_version: 1.79.0
        platform_version: 2019
        toolset: msvc
        arch: x86


    - name: print boost 
      run: dir "${{ steps.install-boost.outputs.BOOST_ROOT }}/lib"

    - name: Configure CMake
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
      run: build_win32.bat
      shell: cmd
      
      #run: |
        #echo %BOOST_ROOT%
        #call 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat'
        #cmake -G "Visual Studio 16 2019" -A x86 -DCMAKE_BUILD_TYPE=Release -S NPLRuntime -B build
